# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-14 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
