# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-07 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200806_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desiption',
            new_name='description',
        ),
    ]
